version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taobao_dw
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taobao_data
    ports:
      - "5432:5432"
    volumes:
      - pg_data_vol:/var/lib/postgresql/data
    restart: always
volumes:
  pg_data_vol: